Increase verbosity of proof generation
spacemeshos/post-rs pull request #119
Opened 2023-08-14 08:01 UTC by reythia

Users currently get very little feedback during proof generation. This leads to concern about whether systems are working properly during the poet window and makes it difficult to understand system performance.

PR contains logging I've personally found useful. 

- (INFO) Inform users when the PoW phase starts and when the Read phase starts.
- (DEBUG) Track number of hashes tried for each nonce group
- (DEBUG) Show when reader starts next postbin file to give some indication of progress - could be expanded to an ETA for time remaining

2023-08-14 08:21 UTC, reythia commented
It would be great to see the time spent finding a nonce and time spent on reading/proving data tracked in metrics harvested by the team. 

I think many users significantly underestimate the PoW aspect when planning their smesh journey and few even realise there's work needed to find a nonce _before_ reading disks.

2023-08-29 13:08 UTC, poszu commented
@reythia, thanks for your contribution. It's true that observability could be improved. I think that what you mentioned about metrics is a great idea and could be extended to events that go-spacemesh already supports (and smapp shows to the user).

Are you willing to work on this PR and drive to completion? Currently, it's not passing CI. If not, then perhaps you could collect the needs in an issue instead and I will take over from there.

2023-08-29 17:06 UTC, reythia commented
I think I've already fixed this in my fork since original PR. I'll try and update the PR.

2023-08-29 17:32 UTC, reythia commented
@poszu Updated

2023-09-03 09:41 UTC, reythia commented
Thanks for suggestions to improve. Updated in line with recommendations.

2023-09-05 06:42 UTC, poszu requested changes
@reythia, thanks. There is still one thing left about the `unwrap()` of a file path.

2023-09-05 07:29 UTC, reythia commented
> @reythia, thanks. There is still one thing left about the `unwrap()` of a file path.

`unwrap()` replaced with `into_owned()`

2023-09-06 09:58 UTC, poszu approved these changes

2023-09-06 10:04 UTC, merged